### ISSUE TITLE
Do PigDiceGame with if, for statements

### ISSUE THREAD

**Issue by dg60866090** [Taehyunn/team-afizz#2]
#Tasks

- [x] Print PigDiceGame rules
- [x] git flow feature start
- [x] touch PigGame.js
- [x] git flow feature finish
- [ ] release git
